### PR TITLE
Test models

### PR DESCRIPTION
**Pull request by jonobrien**
- Stubbed out auth methods for testing later
- stock_transaction test added
- user relationships test added
- SessionsController stubbed out

### CODE REVIEW

**Comment by jdw6359** [comment]
LGTM

**Comment by jonobrien** [comment]
definitely not 32 at all

**Comment by jdw6359** [comment]
Yeah wut

**Comment by jonobrien** [comment]
I incorrectly referenced an issue :+1:

**Comment by jonobrien** [comment]
closes #31

**Pull request merged**
